name: App

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      include_testnets:
        required: true
        type: boolean
      web3auth_network:
        required: true
        type: string
    secrets:
      SUPABASE_URL:
        required: true
      SUPABASE_FUNCTIONS_URL:
        required: true
      SUPABASE_ANON_KEY:
        required: true
      NETLIFY_AUTH_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true
      SENTRY_DSN:
        required: true
      INFURA_KEY:
        required: true
      BLOCKNATIVE_KEY:
        required: true
      WEB3AUTH_CLIENT_ID:
        required: true
      RAMP_API_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit message
        id: get_commit_message
        run: |
          echo "commit_message=$(echo "${{ github.event.head_commit.message }}" | head -n 1)" >> $GITHUB_OUTPUT

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install --force

      - name: Build
        run: CI=false npm run build
        env:
          REACT_APP_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          REACT_APP_SUPABASE_FUNCTIONS_URL: ${{ secrets.SUPABASE_FUNCTIONS_URL }}
          REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          REACT_APP_ENV: ${{ inputs.env }}
          REACT_APP_INFURA_KEY: ${{ secrets.INFURA_KEY }}
          REACT_APP_BLOCKNATIVE_KEY: ${{ secrets.BLOCKNATIVE_KEY }}
          REACT_APP_INCLUDE_TESTNETS: ${{ inputs.include_testnets }}
          REACT_APP_WEB3AUTH_NETWORk: ${{ inputs.web3auth_network }}
          REACT_APP_WEB3AUTH_CLIENT_ID: ${{ secrets.WEB3AUTH_CLIENT_ID }}
          REACT_APP_RAMP_API_KEY: ${{ secrets.RAMP_API_KEY }}

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir app/build --prod --message \"${{ steps.get_commit_message.outputs.commit_message }}\"
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
