name: Functions

on:
  workflow_call:
    secrets:
      SUPABASE_ACCESS_TOKEN:
        required: true
      SUPABASE_PROJECT_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.37.1

      - name: deploy balances
        run: supabase functions deploy balances --project-ref $PROJECT_ID
      - name: deploy get-access-token
        run: supabase functions deploy get-access-token --no-verify-jwt --project-ref $PROJECT_ID
      - name: deploy ramp-callback
        run: supabase functions deploy ramp-callback --no-verify-jwt --project-ref $PROJECT_ID
      - name: deploy send-invitation
        run: supabase functions deploy send-invitation --project-ref $PROJECT_ID
      - name: deploy send-notification
        run: supabase functions deploy send-notification --project-ref $PROJECT_ID
