name: Functions

on:
  push:
    branches: [refactor-github-action]
  workflow_dispatch:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      app: ${{ steps.filter.outputs.app }}
      functions: ${{ steps.filter.outputs.functions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app:
              - 'app/**'
            functions:
              - 'supabase/functions/**'

  Functions:
    needs: changes
    if: ${{ needs.changes.outputs.functions == 'true' }}
    uses: ./.github/workflows/functions.yaml
    secrets:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID_STAGING }}

  App:
    needs: changes
    if: ${{ needs.changes.outputs.app == 'true' }}
    uses: ./.github/workflows/app.yaml
    with:
      env: staging
      include_testnets: true
      web3auth_network: testnet
    secrets:
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID_STAGING }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_STAGING }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGING }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
      BLOCKNATIVE_KEY: ${{ secrets.BLOCKNATIVE_KEY }}
      WEB3AUTH_CLIENT_ID: ${{ secrets.WEB3AUTH_CLIENT_ID_STAGING }}
      RAMP_API_KEY: ${{ secrets.RAMP_API_KEY_STAGING }}
